baseURL = "/"
languageCode = "zh-CN"
title = "LTBY导航"
theme = "hugo-webstack"

# 保留大写路径
disablePathToLower = true

copyright = "ltby"

[params]
  keywords = "网址导航,webstack,hugo"
  description = "Webstack Hugo版主题,网址导航"

[params.search]
  enable = true

[params.darkmode]
  enable = false

[params.edit]
  enable = true
  url = "https://github.com/ltby123/ltby/blob/main/data/webstack.yml"

[params.github]
  enable = true
  url = "https://github.com/oulh/nav"

[permalinks]
  404 = "/404.html"

[params.pinyin]
  enable = true
